const SITEMAP_XML = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://tn-election-dashboard.vercel.app/</loc>
    <lastmod>2026-04-02</lastmod>
    <changefreq>daily</changefreq>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>https://tn-election-dashboard.vercel.app/forecast</loc>
    <lastmod>2026-04-02</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://tn-election-dashboard.vercel.app/results</loc>
    <lastmod>2026-04-02</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://tn-election-dashboard.vercel.app/candidates</loc>
    <lastmod>2026-04-02</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://tn-election-dashboard.vercel.app/trends</loc>
    <lastmod>2026-04-02</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://tn-election-dashboard.vercel.app/news</loc>
    <lastmod>2026-04-02</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://tn-election-dashboard.vercel.app/map</loc>
    <lastmod>2026-04-02</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://tn-election-dashboard.vercel.app/voters</loc>
    <lastmod>2026-04-02</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://tn-election-dashboard.vercel.app/criminal</loc>
    <lastmod>2026-04-02</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://tn-election-dashboard.vercel.app/constituency</loc>
    <lastmod>2026-04-02</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://tn-election-dashboard.vercel.app/comparison</loc>
    <lastmod>2026-04-02</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://tn-election-dashboard.vercel.app/mla-tracker</loc>
    <lastmod>2026-04-02</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://tn-election-dashboard.vercel.app/finance</loc>
    <lastmod>2026-04-02</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://tn-election-dashboard.vercel.app/development</loc>
    <lastmod>2026-04-02</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://tn-election-dashboard.vercel.app/ask</loc>
    <lastmod>2026-04-02</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.6</priority>
  </url>
  <url>
    <loc>https://tn-election-dashboard.vercel.app/about</loc>
    <lastmod>2026-04-02</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
  </url>
  <url>
    <loc>https://tn-election-dashboard.vercel.app/privacy</loc>
    <lastmod>2026-04-02</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.3</priority>
  </url>
  <url>
    <loc>https://tn-election-dashboard.vercel.app/terms</loc>
    <lastmod>2026-04-02</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.3</priority>
  </url>
</urlset>`;

export default function handler(req, res) {
  res.setHeader('Content-Type', 'application/xml; charset=utf-8');
  res.setHeader('Cache-Control', 'public, max-age=3600, s-maxage=3600');
  res.status(200).send(SITEMAP_XML);
}
